### PR TITLE
feature(subscription): Add subscription endpoint

### PR DESCRIPTION
**Pull request by samedguener**
Hi all,

this PR adds an endpoint (`/subscriptions`) to add subscriptions using `POST`. A typical request looks as following:

```json
{
 "email" : "example@example.com",
 "grammarInterested" : false,
 "cultureInterested" : false,
 "historyInterested" : false,
 "foodInterested" : false
}
```

The response will be either 
```json
{
 "status" : "Success",
 "description" : "Email is successfully subscribed!"
}
```
or  
```json
{
 "status" : "Failure",
 "description" : "Email is already subscribed!"
}
```

The email is then added to a Google Firestore collection to keep track.

Best,
Samed

### CODE REVIEW

**Comment by samedguener** [comment]
@samedguener : Find a suitable way to unit test functions

**Comment by samedguener** [comment]
This is how it looks after a successful insertion at Firestore:
image

**Comment by Simsso** [comment]
Two comments:

* The casing in the JSON response fields is inconsistent (`Description` is capitalized)
* For the response you might want to introduce some standard for your API, e.g. always have the `status` (which you already did; however, isn't the status code already telling that?) and then something like `body` where an object goes. Just a suggestion, maybe look at some other APIs and how they do it. [GitHub](https://developer.github.com/v3/) is an example.

**Comment by samedguener** [comment]
Thanks for the feedback !

- I will correct that.
- Regarding the status code. I am following this: https://stackoverflow.com/a/53144807 . But yes, this 
   will be somewhat the standard of the api for `POST`, `DELETE` and `PUT`.

**Pull request merged**
